### PR TITLE
alucard_hotplug: min_cpus_online be 1

### PR DESCRIPTION
**Pull request by ericfrs**

### CODE REVIEW

**Comment by ericfrs** [comment]
Now in suspend/standby all max 2 cores work properly

**Comment by zeeshanhussain** [comment]
@srfarias  what about a workaround like this https://github.com/zeeshanhussain/inazuma-mm-new/commit/b702317325e933481a7d9279a32ca6c950da7d0a

**Comment by ericfrs** [comment]
¿"for otus and condor"? Otus and condor have snap200 but otus (like surnia) is a quad core device ( Snap 200 Msm8212). 

In my opinion **.min_cpus_online**  for otus/surnia should be 2, or 1 if we are sure that this doesn't affect performance, and 1 for condor (there is no way that be 4).

**Comment by zeeshanhussain** [comment]
I will check that thanks

**Pull request merged**
